# Meta tags
author = "Yi Zhou"
description = "A blog about statistics and other stuff."

# Social links
email = "Yi.Zhou@uga.edu"
twitter = "_y1zhou"
github = "y1zhou"
google_scholar = "afMR9NEAAAAJ"
linkedin = "yizhouuga"

# Search in site
minisearch_enabled = true

# Cloudflare analytics
cf_analytics = "8e8b2ef931004c278abd40e84f8e1caa"
