title = "Yi's Knowledge Base"
copyright = "2019-{year}"

baseurl = "http://www.y1zhou.com/"
languageCode = "en-us"
theme = "hugo-northeast"
enableGitInfo = true
relativeURLs = true

# Google Analytics
googleAnalytics = "UA-86032708-3"

# Blogdown settings
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "dracula"
    tabWidth = 2
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = true

[outputs]
    home = ["HTML", "RSS", "MiniSearch"]

[outputFormats.MiniSearch]
    mediaType = "application/json"
    baseName = "minisearch"
    isPlainText = true
    notAlternative = true
